### GET ALL
GET http://localhost:3000/api/especialidades

### POST
# @name createEspecialidad
POST http://localhost:3000/api/especialidades
Content-Type: application/json

{
    "name": "Emilio",
    "description": "esto es una pruebaa"
}

###ID
@id = {{createEspecialidad.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/especialidades/{{id}}

### PUT
PUT http://localhost:3000/api/especialidades/{{id}}
Content-Type: application/json

{
    "name": "Juan",
    "description": "es es una prueba 2"
}

### POST 2
POST http://localhost:3000/api/especialidades
Content-Type: application/json

{
    "name": "pedro",
    "description": "dale que vaaa"
}

### POST
# @name createEspecialidadToDelete
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Blaster",
    "description": "A weapon for a less civilized age"
}

### DELETE
@idToDelete = {{createEspecialidadToDelete.response.body.data.id}}

DELETE http://localhost:3000/api/items/{{idToDelete}}